[package]
name = "holochain_state"
version = "0.0.1"
description = "Abstractions for persistence of Holochain state"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_keystore = { version = "0.0.1", path = "../keystore" }
holochain_types = { path = "../types"}
futures = "0.3.1"
thiserror = "1.0.10"
mockall = "0.6.0"
rkv = "=0.10.4"
rmp-serde = "0.14.3"
serde = "1.0.104"
serde_derive = "1.0.104"
failure = "0.1.6"
shrinkwraprs = "0.3.0"
lazy_static = "1.4.0"
owning_ref = "0.4.1"
tempdir = "0.3.7"  # technically a dev-dependency, but is used by code that needs to be accessed by other crates
parking_lot = "0.10.0"
tracing = "0.1.13"
tracing-futures = "0.2.3"
anyhow = "1.0.26"
tokio = { version = "0.2.11", features = ["macros", "rt-threaded", "rt-util", "sync"] }
derive_more = "0.99.3"
async-trait = "0.1.24"
nanoid = "0.3.0"
either = "1.5.0"
holo_hash = { path = "../holo_hash" }

# TODO: can't hook up metrics until a version is pushed for the lazy_static=1.4.0 update
# holochain_metrics = { version = "0.0.46-alpha1" }

[dev-dependencies]

# TODO: this brings in too many assumptions from the previous version,
# but there is a lot of useful stuff here, so will have to refactor all of this later
# holochain_test_utils = { version = "0.0.46-alpha1", path = "../../test_utils" }

[features]
default = ["lmdb_no_tls"]
lmdb_no_tls = []
