[package]
name = "sx_state"
version = "0.0.1"
description = "holochain state"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
sx_types = { path = "../types"}
futures = "0.3.1"
thiserror = "1.0.10"
mockall = "0.6.0"
rkv = { git = "https://github.com/holochain/rkv.git" }
serde = "1.0.104"
serde_derive = "1.0.104"
holochain_persistence_api = "0.0.18"
maplit = "1.0.2"
failure = "0.1.6"
shrinkwraprs = "0.3.0"
lazy_static = "1.4.0"
owning_ref = "0.4.1"
tempdir = "0.3.7"  # technically a dev-dependency, but is used by code that needs to be accessed by other crates
parking_lot = "0.10.0"
bincode = "1.2.1"
tracing = "=0.1.13"

# TODO: can't hook up metrics until a version is pushed for the lazy_static=1.4.0 update
# holochain_metrics = { version = "0.0.42-alpha5" }

[dev-dependencies]
anyhow = "1.0.26"

# TODO: this brings in too many assumptions from the previous version,
# but there is a lot of useful stuff here, so will have to refactor all of this later
# test_utils = { version = "0.0.42-alpha5", path = "../../test_utils" }

[features]
default = ["lmdb_no_tls"]
lmdb_no_tls = []
