[package]
name = "holochain_lmdb"
version = "0.0.1"
description = "Abstractions for persistence of Holochain state via LMDB"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
byteorder = "1.3.4"
chrono = "0.4.6"
derive_more = "0.99.3"
either = "1.5.0"
fallible-iterator = "0.2.0"
failure = "0.1.6"
fixt = { version = "0.0.1", path = "../fixt" }
futures = "0.3.1"
holo_hash = { path = "../holo_hash" }
holochain_keystore = { version = "0.0.1", path = "../holochain_keystore" }
holochain_serialized_bytes = "=0.0.47"
holochain_zome_types = { version = "0.0.1", path = "../holochain_zome_types" }
lazy_static = "1.4.0"
must_future = "0.1.1"
nanoid = "0.3.0"
parking_lot = "0.10"
rand = "0.7"
rkv = "=0.10.4"
rmp-serde = "0.14.3"
serde = "1.0.104"
serde_derive = "1.0.104"
shrinkwraprs = "0.3.0"
tempdir = "0.3.7"
thiserror = "1.0.23"
tokio = { version = "0.2.11", features = [ "macros", "rt-threaded", "rt-util", "sync" ] }
tokio_safe_block_on = "0.1.2"
tracing = "0.1.18"
tracing-futures = "0.2"

[dev-dependencies]
observability = { version = "0.1" }

[features]
default = [ "lmdb_no_tls", "test_utils" ]
lmdb_no_tls = [ ]
test_utils = [ ]
