[package]
name = "test_wasm_must_get"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2021"

[lib]
name = "test_wasm_must_get"
crate-type = [ "cdylib", "rlib" ]

[[example]]
name = "integrity_test_wasm_must_get"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
holochain_test_wasm_common = { path = "../../../wasm_common" }
hdk = { path = "../../../../hdk" }
thiserror = "1"
hdi = { path = "../../../../hdi" }

[features]
default = []
mock = ["hdk/mock"]
