[package]
name = "influxive-downloader"
version = "0.0.6-dev.0"
description = "Influxive system download utility"
documentation = "https://docs.rs/influxive-downloader"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/holochain"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["metrics"]
categories = ["development-tools"]

[dependencies]
influxive-core = { version = "0.0.6-dev.0", path = "../influxive-core" }

base64 = "0.22"
digest = "0.10"
dirs = "6"
flate2 = "1"
futures = "0.3"
hex = "0.4"
hex-literal = "1.1"
reqwest = { version = "0.12", features = ["rustls-tls", "stream"] }
sha2 = "0.10"
tar = "0.4"
tempfile = "3"
tokio = { version = "1" }
zip = "3.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
