[package]
name = "holochain_keystore"
version = "0.0.1"
description = "keystore for libsodium keypairs"
license = "Apache-2.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "nacl", "libsodium", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
ghost_actor = "0.2.1"
holo_hash = { version = "0.0.1", path = "../holo_hash", features = ["full"] }
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_serialized_bytes = "=0.0.43"
holochain_zome_types = { path = "../zome_types" }
lair_keystore_api = "=0.0.1-alpha.3"
lair_keystore_client = "=0.0.1-alpha.3"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_bytes = "0.11"
thiserror = "1"
tokio = { version = "0.2", features = [ "full" ] }
tracing = "0.1"
