[package]
name = "observability"
version = "0.1.0"
authors = ["freesig <tom.gowan@holo.host>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
inferno = "0.10.0"
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
thiserror = "1.0.10"
tracing = "=0.1.18"
tracing-core = "=0.1.13"
tracing-flame = "0.1.0"
tracing-serde = "=0.1.1"
tracing-subscriber = "=0.2.10"