[package]
name = "test_wasm_commit_entry"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_commit_entry"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
test_wasm_common = { version = "=0.0.1", path = "../../../wasm_common" }
hdk3 = { path = "../../../../hdk" }
