[package]
name = "test_wasm_bench"
version = "0.0.1"
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"

[lib]
name = "test_wasm_bench"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "integrity_test_wasm_bench"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]


[dependencies]
hdk = { path = "../../../../hdk", optional = true }
serde = "1.0"
holochain_deterministic_integrity = { path = "../../../../holochain_deterministic_integrity" }

[features]
default = ["hdk"]
integrity = []
