[package]
name = "kitsune_p2p_timestamp"
version = "0.3.0-beta-dev.6"
description = "Microsecond-precision timestamp datatype for kitsune_p2p"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/kitsune_p2p_timestamp"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

# Dependencies not needed for integrity.
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "oldtime", "serde"], optional = true }

# Dependencies only needed for full.
rusqlite = { version = "0.29", optional = true }

# Dependencies only needed for testing by downstream crates.
arbitrary = { version = "1.0", features = ["derive"], optional = true }
proptest = { version = "1", optional = true }
proptest-derive = { version = "0", optional = true }

once_cell = { version = "1.4.1", optional = true }
rand = { version = "0.8", optional = true }


[dev-dependencies]
holochain_serialized_bytes = { workspace = true }
serde_yaml = "0.9"

[features]
default = ["chrono"]
now = ["chrono"]

full = ["now"]

fuzzing = [
    "arbitrary",
    "proptest",
    "proptest-derive",
    "once_cell",
    "rand",
]

sqlite-encrypted = [ "rusqlite", "rusqlite/bundled-sqlcipher-vendored-openssl" ]
sqlite = [ "rusqlite", "rusqlite/bundled" ]
