[package]
name = "kitsune_p2p_direct"
version = "0.0.1"
description = "Kitsune P2p Direct Application Framework"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/kitsune_p2p_direct"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
arrayref = "0.3.6"
base64 = "0.13"
derive_more = "0.99"
futures = "0.3.14"
hyper = { version = "0.14", features = ["server","http1","http2","tcp"] }
if-addrs = "0.6"
kitsune_p2p_bootstrap = { version = "0.0.1", path = "../bootstrap" }
kitsune_p2p_direct_api = { version = "0.0.1", path = "../direct_api" }
kitsune_p2p_types = { version = "0.0.14", path = "../types" }
kitsune_p2p = { version = "0.0.15", path = "../kitsune_p2p" }
kitsune_p2p_transport_quic = { version = "0.0.14", path = "../transport_quic" }
kitsune_p2p_proxy = { version = "0.0.14", path = "../proxy" }
rand = "0.8.3"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["preserve_order"] }
structopt = "0.3.21"
sodoken = "=0.0.1"
tokio = { version = "1.11", features = ["full"] }
tokio-tungstenite = "0.14"
tungstenite = "0.13"
url2 = "0.0.6"
