[package]
name = "influxive-otel"
version = "0.0.6-dev.0"
description = "Opentelemetry metrics bindings for influxive-child-svc"
documentation = "https://docs.rs/influxive-otel"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/holochain"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["metrics"]
categories = ["development-tools"]

[dependencies]
influxive-core = { version = "0.0.6-dev.0", path = "../influxive-core" }
opentelemetry_api = { version = "0.20.0", features = ["metrics"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
influxive-writer = { version = "0.0.6-dev.0", path = "../influxive-writer" }
