[package]
name = "tokio_helper"
version = "0.0.1"
authors = ["Stefan Junker <mail@stefanjunker.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.4"
tokio = { version = "1.6", features = [ "full" ]}
num_cpus = "1.8"
futures = "0.3"
