[package]
name = "holochain_orm"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { git = "https://github.com/ThetaSinner/sea-orm.git", rev = "c2439cef6a8c86e07d933b9e538a979bcf3ef7e6", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
num_cpus = "1.13.0"
base64 = "0.22"
sodoken = "0.1.0"
tokio = { version = "1.27", features = ["full"] }

[dev-dependencies]
tempfile = "3.3"

[lints]
workspace = true

[features]
test-utils = []
