[package]
name = "influxive-writer"
version = "0.0.6-dev.0"
description = "Rust utility for efficiently writing metrics to a running InfluxDB instance"
documentation = "https://docs.rs/influxive-writer"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/holochain"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["metrics"]
categories = ["development-tools"]

[dependencies]
influxdb = "0.7"
influxive-core = { version = "0.0.6-dev.0", path = "../influxive-core" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
influxive-child-svc = { version = "0.0.6-dev.0", path = "../influxive-child-svc" }
influxive-downloader = { version = "0.0.6-dev.0", path = "../influxive-downloader" }

hex-literal = "1.1"
tempfile = "3"
