[package]
name = "holochain_deterministic_integrity"
version = "0.0.6-dev.0"
description = "The HDI"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain/tree/develop/crates/holochain_deterministic_integrity"
documentation = "https://docs.rs/holochain_deterministic_integrity"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "holo", "integrity"]
categories = ["cryptography"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = []
trace = ["tracing", "tracing-core", "holochain_integrity_types/tracing"]
mock = ["hdk_derive/mock", "mockall"]

[dependencies]
hdk_derive = { version = "0.0.33", path = "../hdk_derive" }
holo_hash = { version = "0.0.25", path = "../holo_hash" }
holochain_wasmer_guest = "=0.0.77"
# it's important that we depend on holochain_integrity_types with no default
# features, both here AND in holochain_deterministic_integrity_derive, to reduce code bloat
holochain_integrity_types = { version = "0.0.5", path = "../holochain_integrity_types", default-features = false }
paste = "=1.0.5"
serde = "1.0"
serde_bytes = "0.11"
# thiserror = "1.0.22"
tracing = { version = "0.1", optional = true }
tracing-core = { version = "0.1", optional = true }
mockall = { version = "0.10.2", optional = true }


[dev-dependencies]
fixt = { path = "../fixt" }
