[package]
name = "holochain_zome_types"
version = "0.0.1"
description = "Holochain zome types"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
readme = "README.md"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixt = { path = "../fixt", optional = true }
holo_hash = { path = "../holo_hash" }
holochain_serialized_bytes = "=0.0.45"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_bytes = "0.11"
strum = { version = "0.18.0", optional = true }
subtle = "2"
thiserror = "1.0.22"

[features]
fixturators = ["fixt", "strum", "holo_hash/fixturators", ]
default = ["fixturators"]
