[package]
name = "test_wasm_call_remote_callee"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com", "freesig" ]
edition = "2018"

[lib]
name = "test_wasm_call_remote_callee"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk3 = { path = "../../../../hdk" }
serde = "1.0.104"
test_wasm_common = { version = "=0.0.1", path = "../../../wasm_common" }
