[package]
name = "sx_types"
version = "0.0.1"
description = "Holochain common types"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
chrono = "0.4.6"
hcid = "0.0.6"
holochain_json_api = { version = "0.0.36", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
holochain_json_derive = { version = "0.0.36", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
# holochain_locksmith = "0.0.43-alpha3"
lib3h_crypto_api = "0.0.38"
regex = "1.1.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
lazy_static = "1.4.0"
multihash = "0.8.0"
snowflake = "1.3.0"
backtrace = "0.3.27"
tracing = "=0.1.13"
tracing-core = "=0.1.10"
tracing-subscriber = "=0.2.3"
tracing-serde = "=0.1.1"

# possibly dispensable
maplit = "1.0.2"
thiserror = "1.0.10"
derive_more = "0.99.3"
rust-base58 = "0.0.4"
shrinkwraprs = "0.3.0"
