[package]
name = "holochain_types"
version = "0.0.1"
description = "Holochain common types"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"
readme = "README.md"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.24"
backtrace = "0.3.27"
base64 = "0.10.1"
chrono = "0.4.6"
derive_more = "0.99.3"
fixt = { path = "../fixt" }
flate2 = "1.0.14"
futures = "0.3"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_keystore = { version = "0.0.1", path = "../keystore" }
holochain_serialized_bytes = "=0.0.41"
holochain_zome_types = { path = "../zome_types" }
lazy_static = "1.4.0"
multihash = "0.8.0"
must_future = "0.1.1"
nanoid = "0.3"
observability = { path = "../observability" }
rand = "0.7"
regex = "1.1.2"
rust-base58 = "0.0.4"
serde = { version = "1.0.104", features = [ "derive", "rc" ] }
serde_bytes = "0.11"
serde_derive = "1.0.104"
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
shrinkwraprs = "0.3.0"
strum = "0.18.0"
tempdir = "0.3.7"
thiserror = "1.0.10"
tokio = { version = "0.2", features = [ "blocking" ] }
tokio_safe_block_on = "0.1.2"
tracing = "=0.1.18"

[dev-dependencies]
# rmp-serde = "0.14.3"
tokio = { version = "0.2", features = [ "full" ] }
