[package]
name = "sx_types"
version = "0.0.1"
description = "Holochain common types"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
chrono = "0.4.6"
hcid = "0.0.6"
# holochain_locksmith = "0.0.43-alpha3"
lib3h_crypto_api = "0.0.38"
regex = "1.1.2"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = "1.0.51"
lazy_static = "1.4.0"
snowflake = "1.3.0"
backtrace = "0.3.27"
tracing = "=0.1.13"
tracing-core = "=0.1.10"
tracing-subscriber = "=0.2.3"
tracing-serde = "=0.1.1"
holochain_serialized_bytes = "=0.0.38"
holochain_wasmer_common = "=0.0.24"
sx_types_derive = { version = "=0.0.1", path = "../types_derive" }
sx_zome_types = { path = "../zome_types" }

# for test_utils
anyhow = "1.0.26"
tempdir = "0.3.7"

# possibly dispensable
multihash = "0.8.0"
maplit = "1.0.2"
thiserror = "1.0.10"
derive_more = "0.99.3"
rust-base58 = "0.0.4"
shrinkwraprs = "0.3.0"
