[package]
name = "crate::holochain_test_wasm_common"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "crate::holochain_test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/common.rs"

[dependencies]
holochain_serialized_bytes = "=0.0.45"
serde = "=1.0.104"
serde_bytes = "0.11"
hdk3 = { path = "../../hdk" }
