[package]
name = "test_wasm_imports"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_imports"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
wee_alloc = "=0.4.5"
holochain_wasmer_guest = "=0.0.24"
test_wasm_common = { version = "=0.0.1", path = "../../wasm_common" }
holochain_serialized_bytes = "=0.0.36"
serde = "=1.0.104"
sx_zome_types = { version = "=0.0.1", path = "../../../crates/zome_types" }
lazy_static = "1.4.0"
