[package]
name = "holochain_test_wasm_common"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "holochain_test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/lib.rs"

[dependencies]
hdk = { path = "../../hdk" }
holochain_serialized_bytes = "=0.0.49"
serde = "1.0"
serde_bytes = "0.11"
