[package]
name = "holochain_test_wasm_common"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "holochain_test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/lib.rs"

[dependencies]
holochain_serialized_bytes = { path = "../../../../holochain-serialization/crates/holochain_serialized_bytes" }
serde = "=1.0.104"
serde_bytes = "0.11"
hdk3 = { path = "../../hdk3" }
