[package]
name = "holochain_test_wasm_common"
version = "0.0.64"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2021"
description = "Common code for Wasm testing for Holochain"
license = "Apache-2.0"
documentation = "https://docs.rs/holochain_test_wasm_common"

[lib]
name = "holochain_test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/lib.rs"

[dependencies]
hdk = { path = "../../hdk", version = "^0.0.163"}
serde = "1.0"
