[package]
name = "test_wasm_validate"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_validate"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "1.0"
hdk3 = { path = "../../../../hdk3" }
