[package]
name = "kitsune_p2p_direct_test"
version = "0.0.1"
description = "Kitsune P2p Direct Application Framework Test Harness"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/kitsune_p2p_direct_test"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
kitsune_p2p_direct = { version = "0.0.1", path = "../direct" }
kitsune_p2p_transport_quic = { version = "0.0.8-dev.0", path = "../transport_quic" }
kitsune_p2p_proxy = { version = "0.0.8-dev.0", path = "../proxy" }
rand = "0.8.4"
structopt = "0.3.21"
tokio = { version = "1.11", features = ["full"] }
tracing-subscriber = "0.2.19"
