[package]
name = "influxive-child-svc"
version = "0.0.6-dev.0"
description = "Run influxd as a child process"
documentation = "https://docs.rs/influxive-child-svc"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/holochain"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["metrics"]
categories = ["development-tools"]

[dependencies]
influxive-core = { version = "0.0.6-dev.0", path = "../influxive-core" }
influxive-downloader = { version = "0.0.6-dev.0", path = "../influxive-downloader", optional = true }
influxive-writer = { version = "0.0.6-dev.0", path = "../influxive-writer" }

hex-literal = { version = "1.1", optional = true }
tempfile = "3"
tokio = { version = "1" }
tracing = "0.1"

[features]
default = ["download_binaries"]

# compiles in the ability to download release influxd and influx binaries
# as a fallback in case they are not found on the path
download_binaries = ["dep:hex-literal", "influxive-downloader"]
