# An action triggered manually to debug the cached state for `release.yml` and `release-prepare.yml`

name: SSH session

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "value passed to 'runs-on'"
        required: false
        default: "ubuntu-latest"
        type: string
      extend-space:
        description: "extend the runner's space"
        required: false
        default: "false"
        type: string

jobs:
  ssh-session:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extend space
        uses: ./.github/actions/extend-space
        if: ${{ github.event.inputs.runs-on == 'ubuntu-latest'  && github.event.inputs.extend-space == 'true' }}

      - name: Install nix
        uses: cachix/install-nix-action@v26
        if: ${{ github.event.inputs.runs-on != 'multi-arch' }}
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command

      - name: Setup cachix
        uses: cachix/cachix-action@v14
        if: ${{ matrix.platform.runs-on != 'multi-arch' }}
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Restart nix-daemon
        if: ${{ github.event.inputs.runs-on == 'ubuntu-latest' }}
        run: |
          sudo bash -c 'echo extra-experimental-features = impure-derivations >> /etc/nix/nix.conf'
          sudo systemctl stop nix-daemon

      - name: debug
        run: |
          set -x
          env
          nix-shell --version
          nix --version
          pwd
