[package]
name = "holochain_diagnostics"
version = "0.0.1"
description = "Tools and patterns for writing Holochain diagnostic tests"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/holochain_diagnostics"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "holo"]
edition = "2021"

# reminder - do not use workspace deps
[dependencies]
anyhow = "1.0"
holochain = { path = "../holochain", default-features = false, features = [
  "sweettest",
  "hdk",
] }
kitsune_p2p = { path = "../kitsune_p2p/kitsune_p2p" }
human-repr = "1"
rand = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3.16"

crossterm = "0.27"
tui = "0.19"

[lints]
workspace = true

[features]
wasmer_sys = ["holochain/wasmer_sys"]
wasmer_wamr = ["holochain/wasmer_wamr"]